"""Initial

Revision ID: 724eeb7059e6
Revises: d92675e13a99
Create Date: 2021-10-23 19:13:29.960508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '724eeb7059e6'
down_revision = 'd92675e13a99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
