"""fixed bugs

Revision ID: 9a0e558e93e3
Revises: d4d67f66fc80
Create Date: 2021-10-21 04:19:46.848106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a0e558e93e3'
down_revision = 'd4d67f66fc80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
