"""ondelete cascade tasksresults

Revision ID: 9d3f3d733267
Revises: 9a0e558e93e3
Create Date: 2021-10-22 15:47:46.682928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d3f3d733267'
down_revision = '9a0e558e93e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('tasks_results_message_id_fkey', 'tasks_results', type_='foreignkey')
    op.drop_constraint('tasks_results_task_id_fkey', 'tasks_results', type_='foreignkey')
    op.create_foreign_key(None, 'tasks_results', 'messages', ['message_id'], ['message_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'tasks_results', 'tasks', ['task_id'], ['task_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks_results', type_='foreignkey')
    op.drop_constraint(None, 'tasks_results', type_='foreignkey')
    op.create_foreign_key('tasks_results_task_id_fkey', 'tasks_results', 'tasks', ['task_id'], ['task_id'])
    op.create_foreign_key('tasks_results_message_id_fkey', 'tasks_results', 'messages', ['message_id'], ['message_id'])
    # ### end Alembic commands ###
