"""Initial

Revision ID: 9e054447fbec
Revises: a6600fa4b792
Create Date: 2021-10-21 03:24:59.697147

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e054447fbec'
down_revision = 'a6600fa4b792'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_user_id_chat_id_key', 'users', type_='unique')
    op.create_unique_constraint(None, 'users', ['client_id', 'chat_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.create_unique_constraint('users_user_id_chat_id_key', 'users', ['user_id', 'chat_id'])
    # ### end Alembic commands ###
